; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1-n16r8v]
platform = espressif32
board = esp32-s3-devkitc-1-n16r8v
framework = espidf

; The values provided for MCPWM outputs and encoder inputs matches the GPIO ports used for the Left Motor of the robot
build_flags =
     -D CONFIG_BDC_MCPWM_GPIO_A=6      ; GPIO6 for MCPWM signal A 
     -D CONFIG_BDC_MCPWM_GPIO_B=7      ; GPIO7 for MCPWM signal B
     -D CONFIG_BDC_ENCODER_GPIO_A=16   ; GPIO16 for rotary encoder signal A
     -D CONFIG_BDC_ENCODER_GPIO_B=15   ; GPIO15 for rotary encoder signal B

monitor_speed = 115200